import Navbar from "@/components/shared/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "@/lib/contexts/CartContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CartProvider>
        <Navbar />
        <main className="flex flex-row">
          <section className="flex min-h-screen flex-1 flex-col items-center bg-dark-1 px-6 pb-10 pt-10 max-md:pb-32 sm:px-10">
            <div className="w-full max-w-8xl">
              {children}
              <Toaster position="top-right" richColors />
            </div>
          </section>
        </main>
      </CartProvider>
    </>
  );
}
